### ISSUE TITLE
Custom type hints

### ISSUE THREAD

**Issue by znicholls** [openscm/OpenSCM-Calibration#23]
It's not clear to me how best to support custom type hints, e.g. defining somewhere something like

```python
from __future__ import annotations

from typing import Any, Union

import numpy as np
import numpy.typing as nptype

NPAnyFloat = np.floating[Any]
"""Numpy float of any type"""

NPAnyInt = np.integer[Any]
"""Numpy integer of any type"""

NPArrayFloatOrInt = nptype.NDArray[Union[NPAnyFloat, NPAnyInt]]
"""Numpy array of float or int type"""
```

And then elsewhere re-using the hints e.g.

```python
from openscm_calibration.type_hints import NPArray

res: NPArray = np.array([1, 2, 3])
```

The issue with this solution is that, if it is ever imported, the `type_hints` module gets executed. As a result, `type_hints` is only importable in Python 3.9 if you use `Union[NPAnyFloat, NPAnyInt]` i.e. you can't use `NPAnyFloat | NPAnyInt`.  That might be ok (it's not clear that a user would ever need to import this annotation at runtime) and the end of the conversation.

However, let's assume we want all our modules to be importable. Turning off this runtime incompatible typing is supported by ruff (https://beta.ruff.rs/docs/settings/#keep-runtime-typing) but it feels like something is wrong if you have to activate this setting. However, I can't work out what else to do. If I put everything behind an `if TYPE_CHECKING` block like the below, then sphinx complains instead that it can't resolve the type hints instead.

```python
from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from typing import Any, Union

    import numpy as np
    import numpy.typing as nptype

    NPAnyFloat = np.floating[Any]
    """Numpy float of any type"""

    NPAnyInt = np.integer[Any]
    """Numpy integer of any type"""

    NPArrayFloatOrInt = nptype.NDArray[Union[NPAnyFloat, NPAnyInt]]
    """Numpy array of float or int type"""
```

This package uses the 'define custom types' pattern (https://github.com/NeilGirdhar/tjax/blob/main/tjax/_src/annotations.py) so it seems like it might not be a completely terrible idea, but maybe I just shouldn't be trying to derive these types in the first place.

**Comment by znicholls** [comment]
@lewisjared and @mikapfl do you have any quick thoughts? I suspect this could appear in many contexts

**Comment by mikapfl** [comment]
I think in this specific case, just write
```python
import numpy as np
import numpy.typing

res: np.typing.NDArray[np.number] = np.array([1, 2, 3])
```
using [numpy's built-in catch-all numeric type](https://numpy.org/devdocs/reference/arrays.scalars.html#numpy.number). More generally, I don't really see a problem with importing type stuff at runtime.

**Comment by lewisjared** [comment]
I don't really get what the problem is. The first example is valid py3.9 right?

If Python 3.9 is being targeted, you should have to write code that is python 3.9 compatible rather than relying that it won't be imported. I use `TYPE_CHECKING` blocks for preventing circular imports (not sure if that is technically a code smell where interfaces aren't independent of their implementation, but that is a debate for another day and isn't how a lot of Python code is written)

**Comment by znicholls** [comment]
> using [numpy's built-in catch-all numeric type](https://numpy.org/devdocs/reference/arrays.scalars.html#numpy.number). More generally, I don't really see a problem with importing type stuff at runtime.

Wow thank you, I fully failed to find this!

> I don't really get what the problem is. The first example is valid py3.9 right?

So what is weird is this:

This is valid Python 3.9

```python
from __future__ import annotations

a: float | int = 9
```

However, this isn't

```python
from __future__ import annotations

float_or_int = float | int  # explodes at runtime because it's not hidden by a type hint

a: float_or_int = 9
```

So I was trying to work out a way to define (the numpy equivalent of) `float | int`, without breaking things. Everything I could think of felt wrong, even though I thought I was trying be more DRY (which I thought is a good thing). Maybe it just can't be done.

The below is fine, but it feels silly to have to use more old school syntax in order to stay DRY.

```python
from __future__ import annotations

from typing import Union

float_or_int = Union[float, int]

a: float_or_int = 9
```

This works at run time, but then seems to break sphinx (particularly if the type definition isn't in the same file)

```python
from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    float_or_int = float | int  # fine at runtime, but causes issues for sphinx

a: float_or_int = 9
```

**Comment by lewisjared** [comment]
Ahh the issue is clearer now. I didn't realise the subtle difference as I haven't tended to use `__future__.annotations`

 > feels silly to have to use more old school syntax in order to stay DRY

Depends on what you are trying to do. If the use of a shared type results in code that is easier to understand *and* you want to support Python 3.9 I think it's a no-brainer to use a Union. It is still obvious what you are trying to achieve which is more important than mixing `Union` and `|` in a few specific locations. The other options are working around the fact that the "|" isn't supported (without the `__future__` package).

**Comment by znicholls** [comment]
Ok cool.

Conclusion: don't get too hung up on the slight imperfection in the interaction between `from __future__ import annotations` and everything else. If we need to add a `type_hinting.py` module in future, just do it and use syntax that is supported by whatever our lowest supported Python version is (even if that introduces slight inconsistencies in some places).
